import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export class PDFGenerator {
  static async generateReport(
    signature1: File,
    signature2: File,
    similarity: number,
    threshold: number = 85
  ): Promise<void> {
    const pdf = new jsPDF();
    const isMatch = similarity >= threshold;

    // Add title
    pdf.setFontSize(20);
    pdf.setTextColor(40, 40, 40);
    pdf.text('Signature Verification Report', 20, 30);

    // Add date
    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 40);

    // Add result summary
    pdf.setFontSize(16);
    pdf.setTextColor(isMatch ? 0 : 220, isMatch ? 150 : 20, isMatch ? 0 : 20);
    pdf.text(`Result: ${isMatch ? 'VERIFIED ✓' : 'FAILED ✗'}`, 20, 60);

    // Add similarity score
    pdf.setFontSize(14);
    pdf.setTextColor(40, 40, 40);
    pdf.text(`Similarity Score: ${similarity.toFixed(1)}%`, 20, 80);
    pdf.text(`Threshold: ${threshold}%`, 20, 95);

    // Add signature images
    try {
      const img1 = await this.fileToBase64(signature1);
      const img2 = await this.fileToBase64(signature2);

      pdf.text('Signature 1:', 20, 120);
      pdf.addImage(img1, 'JPEG', 20, 130, 80, 60);

      pdf.text('Signature 2:', 110, 120);
      pdf.addImage(img2, 'JPEG', 110, 130, 80, 60);

      // Add analysis details
      pdf.setFontSize(12);
      pdf.text('Analysis Details:', 20, 210);
      pdf.text('• Images resized to 300x300 pixels for comparison', 25, 225);
      pdf.text('• Converted to grayscale for processing', 25, 235);
      pdf.text('• Structural Similarity Index (SSIM) algorithm used', 25, 245);
      pdf.text(`• Comparison completed at ${new Date().toLocaleTimeString()}`, 25, 255);

      // Add footer
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Signature Verification System', 20, 280);

    } catch (error) {
      console.error('Error adding images to PDF:', error);
      pdf.text('Error: Could not load signature images', 20, 130);
    }

    // Save the PDF
    const fileName = `signature_verification_${Date.now()}.pdf`;
    pdf.save(fileName);
  }

  private static fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result as string;
        resolve(result);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }
}